# on cadvisor container start, set a key under monitored hosts.
[template]
src   = "prometheus.yml"
dest  = "/etc/prometheus/prometheus.yml"
uid = 0
gid = 0
mode  = "0644"
keys = [
  "/deis/monitor",
]
reload_cmd = "kill -HUP `cat /var/spool/prometheus.pid`" # @fixme: fine for demo, improve later
