apiVersion: v1
kind: Service
metadata:
  name: deis-monitor-prometheus
  labels:
    heritage: deis
spec:
  ports:
  - name: http
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: NodePort
  selector:
    app: deis-monitor-prometheus
