apiVersion: v1
kind: Service
metadata:
  name: deis-monitor-alert
  labels:
    app: deis-monitor-alert
    heritage: deis
spec:
  ports:
  - name: http
    port: 9093
    targetPort: 9093
    protocol: TCP
  selector:
    app: deis-monitor-alert
