#!/bin/bash
echo "Building config.toml!"
./envtpl -in config.toml.tpl >> config.toml
echo "Finished building toml..."
echo "###########################################"
echo "###########################################"
cat config.toml
echo "###########################################"
echo "###########################################"
exec /telegraf -config config.toml
