# expand to all the things
notification_config {
  name: "alertmanager_deis"
{{ if exists "/deis/monitor/alertmanager/slack_webhook_url" }}
  slack_config {
    webhook_url: "{{ getv "/deis/monitor/alertmanager/slack_webhook_url" }}"
    channel: "#{{ getv "/deis/monitor/alertmanager/slack_webhook_channel" }}"
    send_resolved: true
  }
{{ end }}
{{ if exists "/deis/monitor/alertmanager/sns_topic_arn" }}
  amazon_sns_config {
    topic_arn: "{{ getv "/deis/monitor/alertmanager/sns_topic_arn" }}"
    send_resolved: true
  }
{{ end }}
}

aggregation_rule {
  repeat_rate_seconds: 3600
  notification_config_name: "alertmanager_deis"
}
