grafana:
  org: "deisci"
  pull_policy: "Always"
  docker_tag: canary
  # limits_cpu: "100m"
  # limits_memory: "50Mi"
  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: 5Gi

telegraf:
  org: "deisci"
  pull_policy: "Always"
  docker_tag: canary
  # limits_cpu: "100m"
  # limits_memory: "50Mi"

influxdb:
  # Configure the following ONLY if using an off-cluster Influx database
  url: "my.influx.url"
  database: "kubernetes"
  user: "user"
  password: "password"
  # Configure the following ONLY if you want persistence for on-cluster influxdb
  # GCP PDs and EBS volumes are supported only
  persistence:
    enabled: false # Set to true to enable persistence
    name: deis-monitor-influxdb
    size: 20Gi # PVC size
    
global:
  # Set the location of Workflow's influxdb cluster
  #
  # Valid values are:
  # - on-cluster: Run Influxdb within the Kubernetes cluster
  # - off-cluster: Influxdb is running outside of the cluster and credentials and connection information will be provided.
  influxdb_location: "on-cluster"
  # Set the location of Workflow's grafana instance
  #
  # Valid values are:
  # - on-cluster: Run Grafana within the Kubernetes cluster
  # - off-cluster: Grafana is running outside of the cluster
  grafana_location: "on-cluster"
  # Set the location of Workflow's logger-specific Redis instance
  #
  # Valid values are:
  # - on-cluster: Run Redis within the Kubernetes cluster
  # - off-cluster: Run Redis outside the Kubernetes cluster (configure in loggerRedis section)
  logger_redis_location: "on-cluster"